import { ogpTitleAtom } from "@/atoms";
import { useAtomValue } from "jotai";
import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  const ogpTitle = useAtomValue(ogpTitleAtom);
  return (
    <Html lang="ja">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {ogpTitle ? (
          <meta
            property="og:image"
            content={`${process.env.NEXT_PUBLIC_OGP_BASEURL}/api/og?title=めっちゃはやくちでしゃべりたい`}
          />
        ) : (
          <meta property="og:image" content="/public/staticOgp.svg" />
        )}
        <link
          rel="icon"
          href="https://twemoji.maxcdn.com/v/latest/svg/1f5e8.svg"
        />
        <link
          href="https://fonts.googleapis.com/earlyaccess/nicomoji.css"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
